### ISSUE TITLE
Possible bug in gettign a field

### ISSUE THREAD

**Issue by ieugen** [katharsis-project/katharsis-core#152]
Hello, 

I think I've discovered a bug in the current code or I'm doing something different. I'm working on integrating jsonpai with a vertx app. 

Field get (never passess JsonPath building)
```
        router.get("/:id/:field").handler(ctx -> {
            BaseResponse<?> katharsisResponse = null;
            boolean passToMethodMatcher = false;
            try {
                String path = ctx.request().path();
                JsonPath jsonPath = new PathBuilder(resourceRegistry).buildPath(path);
                RequestParams requestParams = createRequestParams(ctx);
                RequestBody requestBody = inputStreamToBody(ctx.getBody().getBytes());

                katharsisResponse = fieldResourceGet.handle(jsonPath, requestParams, requestBody);
                ctx.response().end(Json.encode(katharsisResponse));
            } catch (Exception e1) {
                throw Throwables.propagate(e1);
            }
        });
```

However it fails with : 

```
io.katharsis.resource.exception.ResourceFieldNotFoundException: brandColor
	at io.katharsis.request.path.PathBuilder.getNonResourcePath(PathBuilder.java:101) ~[katharsis-core-1.0.1.jar:?]
	at io.katharsis.request.path.PathBuilder.buildPath(PathBuilder.java:64) ~[katharsis-core-1.0.1.jar:?]
	at profilesrd.khatarsis.KatharsisRestApi.lambda$createRouter$3(KatharsisRestApi.java:179) ~[classes/:?]
```

I've tracked the issue to this piece of code in class **PathBuilder** : 
```
    private JsonPath getNonResourcePath(JsonPath previousJsonPath, String elementName, boolean relationshipMark) {
        String previousElementName = previousJsonPath.getElementName();
        RegistryEntry previousEntry = resourceRegistry.getEntry(previousElementName);
        Set<ResourceField> resourceFields = previousEntry.getResourceInformation().getRelationshipFields();
        for (ResourceField field : resourceFields) {
            if (field.getName().equals(elementName)) {
                if (relationshipMark) {
                    return new RelationshipsPath(elementName);
                } else {
                    return new FieldPath(elementName);
                }
            }
        }
        //TODO: Throw different exception? element name can be null..
        throw new ResourceFieldNotFoundException(elementName);
    }
```

It is trying to get a relationship field (**previousEntry.getResourceInformation().getRelationshipFields()**) instead of an attribute

**Comment by ieugen** [comment]
The field I'm trying to get is not itself a resource.

**Comment by meshuga** [comment]
The path `"/:id/:field"` refers to a related resource URL. Fields doesn't have separate URL.

Plus, `Json.encode(katharsisResponse)` won't work, because `Json` class doesn't allow modules registration - Katharsis uses Jackson for (de)serialization: https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/json/Json.java#L58 :wink: 
And `katharsisResponse = fieldResourceGet.handle(jsonPath, requestParams, requestBody);` should be in `executeBlocking()` :cry:

**Comment by ieugen** [comment]
@meshuga thanks. I use blockingHanlder() for db access.  I'm not sure what you mean by Json.encode() not working. 

I have some code that looks like this:
```
        JsonApiModuleBuilder jsonApiModuleBuilder = new JsonApiModuleBuilder();
        objectMapper.registerModule(jsonApiModuleBuilder.build(resourceRegistry));
```
and I get:
```
{"data":{"type":"accounts","id":"1","attributes":{"brandColor":null,"displayName":null,"name":"ids","credit":0,"brandLogo":null},"relationships":{},"links":{"self":"/katharsis/accounts/1"}},"included":[]}
```

**Comment by meshuga** [comment]
@ieugen  great! :+1:
