### ISSUE TITLE
Spring Boot app fails to start if there is a @Transactional annotation on class implementing RelationshipRepository

### ISSUE THREAD

**Issue by szubtsovskiy** [katharsis-project/katharsis-core#260]
One more problem when using `@Transactional` repositories in Katharsis. If I try to implement RelationshipRepository instead of annotating the class with `@JsonApiRelationshipRepository` I get the following exception on the application startup:

> Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.katharsis.resource.registry.ResourceRegistry]: Factory method 'resourceRegistry' threw exception; nested exception is org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'circleRelationshipsApi' must be of type [com.bookanything.web.api.CircleRelationshipsApi], but was actually of type [com.sun.proxy.$Proxy104]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:585) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
	... 113 common frames omitted
Caused by: org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'circleRelationshipsApi' must be of type [com.bookanything.web.api.CircleRelationshipsApi], but was actually of type [com.sun.proxy.$Proxy104]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:378) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:220) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:351) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:332) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
	at io.katharsis.spring.SpringServiceLocator.getInstance(SpringServiceLocator.java:22) ~[katharsis-spring-2.3.0.jar:na]
	at io.katharsis.resource.registry.DirectRepositoryEntryBuilder.buildRelationshipRepositories(DirectRepositoryEntryBuilder.java:69) ~[katharsis-core-2.3.0.jar:na]
	at io.katharsis.resource.registry.RepositoryEntryBuilderFacade.buildRelationshipRepositories(RepositoryEntryBuilderFacade.java:45) ~[katharsis-core-2.3.0.jar:na]
	at io.katharsis.resource.registry.ResourceRegistryBuilder.build(ResourceRegistryBuilder.java:67) ~[katharsis-core-2.3.0.jar:na]
	at io.katharsis.resource.registry.ResourceRegistryBuilder.build(ResourceRegistryBuilder.java:41) ~[katharsis-core-2.3.0.jar:na]
	at io.katharsis.spring.boot.KatharsisRegistryConfiguration.resourceRegistry(KatharsisRegistryConfiguration.java:32) ~[katharsis-spring-2.3.0.jar:na]
	at io.katharsis.spring.boot.KatharsisRegistryConfiguration$$EnhancerBySpringCGLIB$$9a748f07.CGLIB$resourceRegistry$0(<generated>) ~[katharsis-spring-2.3.0.jar:na]
	at io.katharsis.spring.boot.KatharsisRegistryConfiguration$$EnhancerBySpringCGLIB$$9a748f07$$FastClassBySpringCGLIB$$1fb4a90d.invoke(<generated>) ~[katharsis-spring-2.3.0.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:355) ~[spring-context-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
	at io.katharsis.spring.boot.KatharsisRegistryConfiguration$$EnhancerBySpringCGLIB$$9a748f07.resourceRegistry(<generated>) ~[katharsis-spring-2.3.0.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
	... 114 common frames omitted

It seems like much harder case than #258 because this problem occurs within Spring. Proxy which is created to handle `@Transactional` beans has `java.lang.reflect.Proxy` as superclass and it is impossible to wire the repo by class in this case.

**Comment by meshuga** [comment]
Well, what do know about how transactions are implemented in Spring? :wink:
As you mentioned, it might be much harder to make Katharsis provide Spring transactional behavior e.g. `TransactionProxyFactoryBean` should be used - at least I think from what I found from Spring docs.

**Comment by szubtsovskiy** [comment]
Well, I don't know much in details. There is a lot of magic done under the
hood.

I don't think we should speak about providing transactional behavior in
Katharsis, this is not Katharsis issue. There is an integration issue which
might be solvable since in the app itself transactional beans are autowired
by class and it works well.

I might look into it because I am curious but since it works with
annotations this issue can be dropped. Unless there is a requirement for
someone to implement interfaces I don't see any point in preferring them
over annotations.

So in the worst case this behaviour could be documented and that's it. In
the best case I'll fix it. :-)

On Wednesday, 9 March 2016, Patryk Orwat <notifications@github.com> wrote:

> Well, what do know about how transactions are implemented in Spring? [image:
> :wink:]
> As you mentioned, it might be much harder to make Katharsis provide Spring
> transactional behavior e.g. TransactionProxyFactoryBean should be used -
> at least I think from what I found from Spring docs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/katharsis-project/katharsis-core/issues/260#issuecomment-194535885>
> .
>


-- 
Sergey Zubtsovskiy
sergey.zubtsovskiy@gmail.com
Skype: szubtsovskiy

**Comment by keithdmoore** [comment]
I am using the 
`@Component`,`@JsonApiRelationshipRepository(source = Project.class, target = Task.class)`,
`@Transactional annotations.  I am NOT seeing this issue occur with 2.2.  I suspect this was introduced since that release.  I am able to reproduce the exception with 2.3.
