### ISSUE TITLE
Saving entities with relationships

### ISSUE THREAD

**Issue by mohlek** [katharsis-project/katharsis-core#352]
Hey guys,
I am having trouble saving entities with relationships. I am using Ember 2.6.1 with Katharsis 2.4.1.

I really don't know what the problem is. Every advise would be awesome!

Warning: Wall of code incoming...

Katharsis produces:
```
09:57:58,864 ERROR [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-39) RESTEASY002010: Failed to execute: javax.ws.rs.NotFoundException: RESTEASY003210: Could not find resource for full path: http://localhost:8080/XXX/role-set
	at org.jboss.resteasy.core.registry.ClassNode.match(ClassNode.java:75)
	at org.jboss.resteasy.core.registry.RootClassNode.match(RootClassNode.java:48)
	at org.jboss.resteasy.core.ResourceMethodRegistry.getResourceInvoker(ResourceMethodRegistry.java:445)
	at org.jboss.resteasy.core.SynchronousDispatcher.getInvoker(SynchronousDispatcher.java:257)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:194)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:284)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:263)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:174)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:793)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

My save request:
```JSON
{
   "data":{
      "attributes":{
         "roleId":"1",
         "moduleId":"1"
      },
      "relationships":{
         "functions":{
            "data":[
               {
                  "type":"module-function",
                  "id":"3"
               },
               {
                  "type":"module-function",
                  "id":"4"
               }
            ]
         },
         "module":{
            "data":{
               "type":"module",
               "id":"1"
            }
         }
      },
      "type":"role-set"
   }
}
```

```curl
curl 'http://api.localdev/role-set' -X PATCH -H 'Origin: http://127.0.0.1:4200' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4' -H 'Authorization: Bearer 8f0f05b9-6a6a-4670-965f-0c0b7ff59b93' -H 'Content-Type: application/vnd.api+json' -H 'Accept: application/vnd.api+json' -H 'Referer: http://127.0.0.1:4200/admin/roles/1' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36' -H 'Connection: keep-alive' -H 'DNT: 1' --data-binary '{"data":{"attributes":{"roleId":"1","moduleId":"1"},"relationships":{"functions":{"data":[{"type":"module-function","id":"3"},{"type":"module-function","id":"4"}]},"module":{"data":{"type":"module","id":"1"}}},"type":"role-set"}}' --compressed
```

```Java
@JsonApiResource(type = "role-set")
public class RoleSet {

	@JsonApiId
	@Id
	@Column
	private Integer						id;

	@Column(name = "ROLE_ID")
	private Integer						roleId;

	@Column(name = "MODULE_ID")
	private transient Integer			moduleId;

	@Column(name = "function")
	private transient Integer			functionId;

	@Column
	private Boolean						value;

	@JsonApiToOne
	@JsonApiIncludeByDefault
	private Module						module;

	@JsonApiToMany
	@JsonApiIncludeByDefault
	private Collection<ModuleFunction>	functions;
...
```

```Java
@JsonApiResource(type = "module")
public class Module {

	@Id
	@JsonApiId
	@Column
	private Integer						id;

	@Column
	private String						name;

	@JsonApiToMany
	@JsonApiIncludeByDefault
	private Collection<ModuleFunction>	functions;
...
```

```Java
@JsonApiResource(type = "module-function")
public class ModuleFunction {

	@JsonApiId
	@Id
	@Column
	private Integer	id;

	@Column(name = "MODULE_ID")
	private Integer	moduleId;

	@Column
	private String	name;

	@Column
	private String	description;
...
```

```Java
@JsonApiResourceRepository(RoleSet.class)
public class RoleSetEndpoint extends APIEndpoint<RoleSet, Integer> {

	/*
	 * (non-Javadoc)
	 * @see org.ddg.DDGRestAPI.util.APIEndpoint#save(java.lang.Object)
	 */
	@Override
	public <S extends RoleSet> S save(S entity) throws Exception {
		System.out.println("Save");
		return super.save(entity);
	}

	/*
	 * (non-Javadoc)
	 * @see org.ddg.DDGRestAPI.util.APIEndpoint#delete(java.io.Serializable)
	 */
	@Override
	public void delete(Integer id) throws Exception {
		System.out.println("Delete " + id);
	}
}
```

```Java
public class ModuleFunctionToRoleSet implements RelationshipRepository<RoleSet, Integer, ModuleFunction, Integer> {
	// private @Inject ModuleFunctionTable moduleFunction;

	/*
	 * (non-Javadoc)
	 * @see io.katharsis.repository.RelationshipRepository#setRelation(java.lang.Object, java.io.Serializable, java.lang.String)
	 */
	@Override
	public void setRelation(RoleSet source, Integer targetId, String fieldName) {
		System.out.println();
	}

	/*
	 * (non-Javadoc)
	 * @see io.katharsis.repository.RelationshipRepository#setRelations(java.lang.Object, java.lang.Iterable, java.lang.String)
	 */
	@Override
	public void setRelations(RoleSet source, Iterable<Integer> targetIds, String fieldName) {
		System.out.println();
	}

	/*
	 * (non-Javadoc)
	 * @see io.katharsis.repository.RelationshipRepository#addRelations(java.lang.Object, java.lang.Iterable, java.lang.String)
	 */
	@Override
	public void addRelations(RoleSet source, Iterable<Integer> targetIds, String fieldName) {
		System.out.println();
	}

	/*
	 * (non-Javadoc)
	 * @see io.katharsis.repository.RelationshipRepository#removeRelations(java.lang.Object, java.lang.Iterable, java.lang.String)
	 */
	@Override
	public void removeRelations(RoleSet source, Iterable<Integer> targetIds, String fieldName) {
		System.out.println();
	}

	/*
	 * (non-Javadoc)
	 * @see io.katharsis.repository.RelationshipRepository#findOneTarget(java.io.Serializable, java.lang.String, io.katharsis.queryParams.QueryParams)
	 */
	@Override
	public ModuleFunction findOneTarget(Integer sourceId, String fieldName, QueryParams queryParams) {
		System.out.println();
		return null;
	}

	/*
	 * (non-Javadoc)
	 * @see io.katharsis.repository.RelationshipRepository#findManyTargets(java.io.Serializable, java.lang.String, io.katharsis.queryParams.QueryParams)
	 */
	@Override
	public Iterable<ModuleFunction> findManyTargets(Integer sourceId, String fieldName, QueryParams queryParams) {
		System.out.println();
		return null;
	}
}
```

Ember role-set.js
```JavaScript
import Model from 'ember-data/model';
import attr from 'ember-data/attr';
import { belongsTo, hasMany } from 'ember-data/relationships';

export default Model.extend({
  roleId: attr('string'),
  moduleId: attr('string'),
  functions: hasMany('module-function'),
  value: attr(),
  module: belongsTo('module')
});
```

Ember module.js
```JavaScript
export default Model.extend({
  name: attr(),
  functions: hasMany('module-function')
});
```

Ember module-function.js
```JavaScript
import Model from 'ember-data/model';
import attr from 'ember-data/attr';
// import { belongsTo } from 'ember-data/relationships';

export default Model.extend({
  name: attr(),
  description: attr()
});
```

**Comment by mohlek** [comment]
it seem that this error is related to #345
