### ISSUE TITLE
ErrorResponseSerializer is missing

### ISSUE THREAD

**Issue by woonsan** [katharsis-project/katharsis-core#44]
It seems that there is no serializer for ErrorResponse by default. As a result, if serializing ErrorResponse (for example, io.katharsis.rs.KatharsisFilter#dispatchRequest() tries to serialize ErrorResponse on KatharsisException), then it should throw an exception like the following:

Caused by: java.lang.IllegalArgumentException: Response can be either class io.katharsis.response.ResourceResponse or class io.katharsis.response.CollectionResponse. Got class io.katharsis.errorhandling.ErrorResponse
	at io.katharsis.jackson.serializer.BaseResponseSerializer.serialize(BaseResponseSerializer.java:49)
	at io.katharsis.jackson.serializer.BaseResponseSerializer.serialize(BaseResponseSerializer.java:23)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:12

It is likely because it doesn't register a serializer for ErrorResponse at the moment.

**Comment by woonsan** [comment]
pull requested: https://github.com/katharsis-project/katharsis-core/pull/45

**Comment by poznachowski** [comment]
We introduced an approach of exception mappers, very similiar as in JAX-RS, but made them JSON:API specific (via @ExceptionMapperProvider and JsonApiExceptionMapper implementations) I will put some usage docs pretty soon @ katharsis.io documentation. However, the ErrorResponseSerializer gives user more options how to handle errors. I will go through the changes and get back to you.

**Comment by poznachowski** [comment]
Indeed, we were missing the ErrorResponse serializer. Thanks!
I need to add an integration test for that as well.
